name: hotspot3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pandas
  - scipy
  - pip
  - numpy
  - statsmodels
  - samtools=1.15.1
  - pybigwig
  - pysam
  - tqdm
  - ca-certificates
  - openssl
  - libflint
  - bedops
  - ucsc-bedgraphtobigwig
  - bioconda::ucsc-bedtobigbed
  - bioconda::mawk
  - bottleneck
  - pywavelets
  - scikit-learn
  - pyarrow
  - networkx
  - pip:
    - babachi==3.0.0
    - genome-tools==2.0.0
    - git+https://github.com/vierstralab/hotspot3


